name: mep
on:  
  workflow_dispatch:
    inputs:
      server:
        description: "Env déploiement"
        required: true
        default: "dev"
jobs: 
  deploy-env:
    
    runs-on: ubuntu-latest
    steps:
      - name: "Démarrage Workflow"
        run: echo "Démarrage du workFlow ${{github.ref}}"
      - name: "Récupération code"
        run: echo "Récupération du code"
        if: ${{ github.ref == 'refs/heads/main2' }}
