name: mep
on:  
  workflow_dispatch:
    inputs:
      server:
        description: "SALUT LES AMIS"
        required: true
jobs: 
  deploy-env:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Démarrage Workflow"
        run: echo "Démarrage du workFlow ${{github.ref}}"
