name: mep
on:  
  workflow_dispatch:
    inputs:
      server:
        description: "Env déploiement"
        required: true
        default: "dev"
jobs: 
  deploy-env:
    
    runs-on: ubuntu-latest
    steps:
      - name: "Démarrage Workflow"
        run: echo "Démarrage du workFlow ${{github.ref}}"
      - name: "Checkout"
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v4.1.1
      - name: "Déploiement Prod"
        run: echo "Déploiement en production"
        if: github.event.inputs.server == 'prod'
      - name: "Déploiement Recette"
        run: echo "Déploiement en recette"
        if: github.event.inputs.server == 'rec'
      - name: "Déploiement Dev"
        run: echo "Déploiement en dev"
        if: github.event.inputs.server == 'dev'

