name: mep
on:  
  workflow_dispatch:
    inputs:
      server:
        description: "Env déploiement"
        required: true
        default: "dev"
jobs: 
  deploy-env:
    
    runs-on: ubuntu-latest
    steps:
      - name: "Démarrage Workflow"
        run: echo "Démarrage du workFlow ${{github.ref}}"
      - name: "Checkout"
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v4.1.1
      - name: "Déploiement Prod"
        if: github.event.inputs.server == "prod"
        run: "Déploiement en production"
